### ISSUE TITLE
toMatchEcho example throws

### ISSUE THREAD

**Issue by ghost** [kahlan/docs#16]
https://github.com/kahlan/kahlan/pull/51 introduced `toMatchEcho` with the following example for the documentation:

```php
expect('Hello World!')->toMatchEcho(function($actual) {
    return $actual === 'Hello World!';
});
```

Which results in the following error when run:

    `Error` Code(0) with message "Call to undefined function Hello World!()"

Whereas the following `toMatch` matcher runs without issue:

```php
expect('Hello World!')->toMatch('/^H(.*?)!$/');
```

I left a comment in the PR introducing the feature. It's not clear if it's a core bug or a documentation issue. But as it stands the example in the docs is not correct.

**Comment by samsonasik** [comment]
There is doc for it: 

```
    $closure = function() {
        echo "Hello World!";
    };

    expect($closure)->toMatchEcho('/^H(.*?)!$/');
```

**Comment by samsonasik** [comment]
@jails I think it is documentation issue ?

**Comment by jhabdas** [comment]
Thanks @samsonasik. I saw that, and that example works. But given there are two examples and one throws is indicative of either bug in the implementation of #51 or a need to update or remove the second example.

**Comment by samsonasik** [comment]
Thank you, I've created PR #17 for it /cc @jails

**Comment by jails** [comment]
Correct the documentation was wrong :+1: 

The matchers are working like so:

```php
expect(function() { echo "Hello World!"; })->toMatchEcho(function($actual) {
    return $actual === 'Hello World!';
});

expect('Hello World!')->toMatch(function($actual) {
    return $actual === 'Hello World!';
});
```

`::toMatchEcho()` check echo outputs which requires code to be isolated in a closure.

**Comment by ghost** [comment]
Word. Thanks for the quick action here guys. I cannot wait to back my WP plugin with a suite of tests using this library. 💯

**Comment by jails** [comment]
You bet !
Just for my curiosity which is the WP plugin you are talking about ?

**Comment by ghost** [comment]
https://github.com/comfusion/hyperdrive
