### ISSUE TITLE
Clarify when Function Stubbing works

### ISSUE THREAD

**Issue by ghost** [kahlan/docs#20]
Under Kahlan 3.x and given the following code snippet:

```php
namespace hyperdrive\spec;
use function hyperdrive\calibrate_thrusters;
use function hyperdrive\get_enqueued_scripts;

describe('calibrate_thrusters()', function () {
  it('expects get_enqueued_scripts() to be called', function () {
    allow('get_enqueued_scripts')
      ->toBeCalled()
      ->andRun(function () { return []; } );
    expect('get_enqueued_scripts')->toBeCalled();
    calibrate_thrusters();
  });
});
```

Where `composer.json` uses what I understand to be _faux_ autoloading for files in order to achieve namespaced function imports in Kahlan:

```json
"autoload": {
  "files": [
    "src/hyperdrive.php"
  ]
}
```

And with consideration to the following document:
https://kahlan.github.io/docs/allow.html

Which states:

> Use `allow()` to stub almost all functions like so:

I believe the part of the blockquote which says <q>almost all functions</q> seems misleading given Kahlan, by way of Composer if I'm not mistaken, [cannot autoload files](https://github.com/kahlan/kahlan/issues/232#issuecomment-289723805). As a result, and with consideration to some of the [related](https://github.com/kahlan/kahlan/issues/232) [issues](https://github.com/kahlan/kahlan/issues/244) surfacing it seems the above line should be updated a caveat of some sort added to clarify what is meant by <q>almost all functions</q>.

Thoughts?

**Aside:** Barring current design, what might it take either in Composer or Kalhan to make something like the above possible otherwise (hoping this isn't a loaded question)?

**Comment by ghost** [comment]
Actually, I need to backpedal a little bit. Sorry, I'm hitting current mental capacity.

When I run the above snippet I actually get the following message:

    `Error` Code(0) with message "Call to undefined function wp_scripts()"

Which means `get_enqueued_scripts` is indeed being called, as it itself calls a magic global `\wp_scripts()` from my method. I'm going to close this as I do more research and experimentation.

**Comment by ghost** [comment]
Okay. So it looks like the functions get called. But `andRun` doesn't take over. I don't need help debugging this. I opened this issue primarily with the desire to seek clarity in the docs.

**Comment by ghost** [comment]
I'm probably just doing something dumb. Let me reopen this when I actually have actionable feedback.

**Comment by ghost** [comment]
Okay. Have some actionable feedback. Consider updating docs and opening an issue against Kahlan if you agree.

When I run the following function following the same pattern as shown in my original code snippet the function runs without the stub substitution and could lead to false positives in test implementation. Here's another snippet as an example:

```php
namespace hyperdrive\spec;

use function hyperdrive\array_moonwalk;
use function hyperdrive\generate_antimatter;
use function hyperdrive\fold_spacetime;

describe('fold_spacetime()', function () {
  given('fixtures', function () {
    return json_decode(
      file_get_contents(__DIR__ . "/fixtures/dependencies.json")
    );
  });
  given('multipleCommonDeepDifferentDepths', function () {
    return $this->fixtures->multipleCommonDeepDifferentDepths;
  });

  it('performs a moonwalk', function () {
    $antimatter = generate_antimatter(
      $this->multipleCommonDeepDifferentDepths
    );
    allow('array_moonwalk')
      ->toBeCalled()
      ->with($antimatter, [])
      ->andReturn('foo');
    $string = fold_spacetime($antimatter);
    print_r($string);
  });
});
```

The output of `print_r` and results of the test run when used with [the test suite](https://github.com/comfusion/hyperdrive/blob/master/spec/hyperdrive.spec.php) I'm putting together does not alter the output of `andReturn`, which would allow the test to pass with bad data.

Back to the initial request and related issues linked I feel docs may want to make mention of which specific conditions under which functions are not included in the set of <q>almost all functions</q>, or possibly amend the statement to remove ambiguity or provide a limitations section (like Patchwork maybe?) in the docs to help users capture the high-level stuff before subbing issues.

**Comment by jails** [comment]
Starting 4.1.x, the Kahlan autoloader is initialized earlier and should now be able to patch files from the following `composer.json` section:
```php
"autoload": {
  "files": [
    "src/somefilewithfunctions.php"
  ]
}
```
