### ISSUE TITLE
Add example of `use` with a closure

### ISSUE THREAD

**Issue by ghost** [kahlan/docs#21]
Given the following snippet:

```php
it('errors if handle is not registered', function () {
  $dependencies = $this->dependencies;
  $dependencies->registered = ['foo' => 'bar'];
  $closure = function () {
    get_dep_for_handle($dependencies, 'baz');
  };
  expect($closure)->toThrow();
});
```

Applied against the following code:

```php
function get_dep_for_handle( $instance, $handle ) {
	return $instance->registered[ $handle ];
}
```

The test passes. But not because of the logical assertion being made. It throws in this case because `$dependencies` is not defined within the scope of the closure. As a result, please consider adding some examples of `use` to the docs to help prevent this kind of false positive from occurring in test implementations.

**Comment by jails** [comment]
I think a good practice is to not use `toThrow()` without parameters since it catches any kind of errors. To be sure we are testing the correct piece of code, adding at least a part of the error message would make sense imo:
 
```php
...
expect($closure)->toThrow("~Undefined index: baz~");
```

**Comment by ghost** [comment]
If my code threw any errors besides none I'd have an entirely different problem 🤣 . But that's a nifty looking feature. I will tuck that under my hat for later.

The crux of this request is to update the docs with some examples of `use` when closures are present as it's likely individuals will try and do what I did if they're still getting used to PHP and think variables will apply to closures within an outer scope (like they do in JS), e.g.

```php
$dependencies = $this->dependencies;
$closure = function () use ($dependencies) {
  get_dependency_data($dependencies, []);
};
```

Good. `$dependencies` available inside function scope.

```php
$dependencies = $this->dependencies;
$closure = function () {
  get_dependency_data($dependencies, []);
};
```

Bad. You only _think_ you're doing it right.

**Comment by ghost** [comment]
Updated comment. LMK if this seems useful and I'll send in a pull.

**Comment by jails** [comment]
That's a good idea :+1: !
