### ISSUE TITLE
Clarify the magicMethods option for Double::instnace

### ISSUE THREAD

**Issue by Khartir** [kahlan/docs#24]
The documentation is a bit unclear what exactly the "magicMethods" option in `Double::instance` does.
From the Docs:
> Note: If the 'extends' option is used, magic methods won't be included, so as to avoid any conflict between your tested classes and the magic methods.

It is unclear, which magic methods aren't included, the ones from the extended class or the default ones kahlan adds.
It should also be mentioned that if an interface defines a magic method the option `'magicMethods => false'` has to be added, otherwise there is a conflict.

**Comment by jails** [comment]
Fair enough for both `'extends'` or `'implements'` options, if sets, default magic methods added by kahlan shouldn't be included anymore.
Since it's a BC break change, the change will happen in the 4.x version.

**Comment by jails** [comment]
Sorry for the delay, this has been fixed in: https://github.com/kahlan/kahlan/commit/5ccef8a5d6a332ff839806facedb4b65ef83ea94
