### ISSUE TITLE
Documentation on Filters usage outdated

### ISSUE THREAD

**Issue by yookoala** [kahlan/docs#26]
As reported in https://github.com/kahlan/kahlan/issues/290, the documentation on how to use a Filter does not work for kahlan 4.0.5.

**Comment by samsonasik** [comment]
could you provide pull request ? Thank you

**Comment by samsonasik** [comment]
I've created PR #27 for it

**Comment by samsonasik** [comment]
Fixed at #27 and deployed

**Comment by yookoala** [comment]
@samsonasik: Thanks :-)
