### ISSUE TITLE
Add more technical details how monkey patching, stubbing, doubles are working

### ISSUE THREAD

**Issue by ddziaduch** [kahlan/docs#30]
Many people are curious how the internals of Kahlan works including me. When I debug I can see the code is replace on the fly by some kind of patcher. It would be great to update the docs and give some details about it :)

**Comment by jails** [comment]
Most of the magic can be summed up like so :
- 1. replacing the composer autoloader by a "custom one"
- 2. parsing and patching php files using different plugins (each one allowing some kind of "control" over the code) before actually loading them.
- 3. loading the modified php files from the `tmp` directory

I wrote a [little something](http://radify.io/blog/aspect-oriented-programming/) a while ago, about Automatic code generation and AOP.

Anyway if you have more specific questions about the core, I'll glad to answer.

**Comment by ddziaduch** [comment]
@jails from what I remember, the patcher only works with Composer's PSR-0 and PSR-4 autoloader. Am I right?

**Comment by jails** [comment]
Yup Kahlan only support PSR-0 and PSR-4 autoloading rules (like composer) and rely on the `autoload.php` file to set things up (through https://github.com/kahlan/kahlan/blob/master/autoload.php).
But you can still manually add some additional rules in your `kahlan-config.php` file like so:
```php
use Kahlan\Filter\Filters;

Filters::apply($this, 'namespaces', function($next) {
  $this->autoloader()->addPsr4('Api\\Models\\', __DIR__ . '/app/models/');
  $this->autoloader()->addPsr4('Api\\Controllers\\', __DIR__ . '/app/controllers/');
  return $next();
});
```

**Comment by ddziaduch** [comment]
Cool thanks @jails !
